name: Python Publish Workflow
on:
  workflow_call:

jobs:
  publish:
    uses: ac-analytics/action-python/.github/workflows/publish.yml@v0.1.1
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
